///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace VodafoneBS_Branding
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login_Recording recording.
    /// </summary>
    [TestModule("d9aa3286-eab1-442d-9474-69e4fff03219", ModuleType.Recording, 1)]
    public partial class Login_Recording : ITestModule
    {
        /// <summary>
        /// Holds an instance of the VodafoneBS_BrandingRepository repository.
        /// </summary>
        public static VodafoneBS_BrandingRepository repo = VodafoneBS_BrandingRepository.Instance;

        static Login_Recording instance = new Login_Recording();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login_Recording()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login_Recording Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Practitest();

            // Opening Vodafone Business Survellaince
            Report.Log(ReportLevel.Info, "Website", "Opening Vodafone Business Survellaince\r\nOpening web site 'https://vodar2737.caas.edgevis.io:9443' with browser 'Edge' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://vodar2737.caas.edgevis.io:9443", "Edge", "", false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Username' at 29;10.", repo.ApplicationUnderTest.UsernameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Username.Click("29;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Shaun' with focus on 'ApplicationUnderTest.Username'.", repo.ApplicationUnderTest.UsernameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Username.PressKeys("Shaun");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Password' at 72;12.", repo.ApplicationUnderTest.PasswordInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Password.Click("72;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'password' with focus on 'ApplicationUnderTest.Password'.", repo.ApplicationUnderTest.PasswordInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Password.PressKeys("password");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Submit' at 93;17.", repo.ApplicationUnderTest.SubmitInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Submit.Click("93;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Users' at 80;67.", repo.ApplicationUnderTest.UsersInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Users.Click("80;67");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='https://vodar2737.caas.edgevis.io:9443/images/logo.png') on item 'ApplicationUnderTest.GoToServerHome'.", repo.ApplicationUnderTest.GoToServerHomeInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ApplicationUnderTest.GoToServerHomeInfo, "Src", "https://vodar2737.caas.edgevis.io:9443/images/logo.png");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=47,Height=47}) on item 'ApplicationUnderTest.GoToServerHome'.", repo.ApplicationUnderTest.GoToServerHomeInfo, new RecordItemIndex(8));
            Validate.ContainsImage(repo.ApplicationUnderTest.GoToServerHomeInfo, GoToServerHome_Screenshot1, GoToServerHome_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Account' at 27;27.", repo.ApplicationUnderTest.AccountInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.Account.Click("27;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Logout' at 124;6.", repo.ApplicationUnderTest.LogoutInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.Logout.Click("124;6");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage GoToServerHome_Screenshot1
        { get { return repo.ApplicationUnderTest.GoToServerHomeInfo.GetScreenshot1(new Rectangle(0, 0, 47, 47)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions GoToServerHome_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
