///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VodafoneBS_Branding
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VodafoneBS_BrandingRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b5eaa830-4a32-43f0-b9c0-bb8e0443eb0a")]
    public partial class VodafoneBS_BrandingRepository : RepoGenBaseFolder
    {
        static VodafoneBS_BrandingRepository instance = new VodafoneBS_BrandingRepository();
        VodafoneBS_BrandingRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the VodafoneBS_BrandingRepository element repository.
        /// </summary>
        [RepositoryFolder("b5eaa830-4a32-43f0-b9c0-bb8e0443eb0a")]
        public static VodafoneBS_BrandingRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VodafoneBS_BrandingRepository() 
            : base("VodafoneBS_BrandingRepository", "/", null, 0, false, "b5eaa830-4a32-43f0-b9c0-bb8e0443eb0a", ".\\RepositoryImages\\VodafoneBS_BrandingRepositoryb5eaa830.rximgres")
        {
            _applicationundertest = new VodafoneBS_BrandingRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b5eaa830-4a32-43f0-b9c0-bb8e0443eb0a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("45e75d1d-fb75-48b9-948c-f0308a8f07ad")]
        public virtual VodafoneBS_BrandingRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class VodafoneBS_BrandingRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("45e75d1d-fb75-48b9-948c-f0308a8f07ad")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _usersInfo;
            GoToServerHomeInfoClass _gotoserverhomeInfo;
            RepoItemInfo _accountInfo;
            RepoItemInfo _logoutInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='vodar2737.caas.edgevis.io:9443']", parentFolder, 30000, null, false, "45e75d1d-fb75-48b9-948c-f0308a8f07ad", "")
            {
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'username']", 30000, null, "ee73ac8f-748f-4b52-8069-3e62462ccab4");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "8f5f7c46-4673-4111-b020-4e85e7db5ca2");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//input[#'submit']", 30000, null, "e21a1843-d8bc-43ad-b6de-cd1a670bde60");
                _usersInfo = new RepoItemInfo(this, "Users", ".//section[#'float']/div/div/div/section/div/div[3]/div[3]", 30000, null, "afc79f51-7139-423f-9a25-a85b664797ea");
                _gotoserverhomeInfo = new GoToServerHomeInfoClass(this);
                _accountInfo = new RepoItemInfo(this, "Account", ".//div[#'userPanel']/span[3]", 30000, null, "741a917b-7294-4c61-8e04-ae253083c7d6");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//div[#'userPanel']//a[@innertext='Logout']", 30000, null, "25460181-175f-456d-b7d2-1d47f6682d87");
            }

            /// <summary>
            /// The GoToServerHomeInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("ac280bd3-7fc4-448a-abe7-e6234d36f315")]
            public class GoToServerHomeInfoClass : RepoItemInfo
            {
                /// <summary>
                /// GoToServerHomeInfoClass class constructor.
                /// </summary>
                public GoToServerHomeInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "GoToServerHome", ".//body[#'top']//a[@title='Go to server home']/img[@alt='Go to server home']", 30000, null, "ac280bd3-7fc4-448a-abe7-e6234d36f315")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("f492d271-c64d-4b13-9c82-843249d377cd")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("f492d271-c64d-4b13-9c82-843249d377cd");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("f492d271-c64d-4b13-9c82-843249d377cd")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("f492d271-c64d-4b13-9c82-843249d377cd", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("45e75d1d-fb75-48b9-948c-f0308a8f07ad")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("45e75d1d-fb75-48b9-948c-f0308a8f07ad")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("ee73ac8f-748f-4b52-8069-3e62462ccab4")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("ee73ac8f-748f-4b52-8069-3e62462ccab4")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("8f5f7c46-4673-4111-b020-4e85e7db5ca2")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("8f5f7c46-4673-4111-b020-4e85e7db5ca2")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("e21a1843-d8bc-43ad-b6de-cd1a670bde60")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("e21a1843-d8bc-43ad-b6de-cd1a670bde60")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The Users item.
            /// </summary>
            [RepositoryItem("afc79f51-7139-423f-9a25-a85b664797ea")]
            public virtual Ranorex.DivTag Users
            {
                get
                {
                    return _usersInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Users item info.
            /// </summary>
            [RepositoryItemInfo("afc79f51-7139-423f-9a25-a85b664797ea")]
            public virtual RepoItemInfo UsersInfo
            {
                get
                {
                    return _usersInfo;
                }
            }

            /// <summary>
            /// The GoToServerHome item.
            /// </summary>
            [RepositoryItem("ac280bd3-7fc4-448a-abe7-e6234d36f315")]
            public virtual Ranorex.ImgTag GoToServerHome
            {
                get
                {
                    return _gotoserverhomeInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The GoToServerHome item info.
            /// </summary>
            [RepositoryItemInfo("ac280bd3-7fc4-448a-abe7-e6234d36f315")]
            public virtual GoToServerHomeInfoClass GoToServerHomeInfo
            {
                get
                {
                    return _gotoserverhomeInfo;
                }
            }

            /// <summary>
            /// The Account item.
            /// </summary>
            [RepositoryItem("741a917b-7294-4c61-8e04-ae253083c7d6")]
            public virtual Ranorex.SpanTag Account
            {
                get
                {
                    return _accountInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Account item info.
            /// </summary>
            [RepositoryItemInfo("741a917b-7294-4c61-8e04-ae253083c7d6")]
            public virtual RepoItemInfo AccountInfo
            {
                get
                {
                    return _accountInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("25460181-175f-456d-b7d2-1d47f6682d87")]
            public virtual Ranorex.ATag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("25460181-175f-456d-b7d2-1d47f6682d87")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
